#!/usr/bin/env bash

# Run mdfmt on all markdown files
gitRoot="$(git rev-parse --show-toplevel || echo .)"

format() {
	if [[ -f "${HOME}/scripts/mdfmt" ]]; then
		"${HOME}/scripts/mdfmt" "$@" &>/dev/null
	fi
}

# Run mdfmt on src/ directory
format "${gitRoot}" && echo "Formatted files successfully"
